/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionCard: typeof import('./src/components/AccordionCard.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CheckRow: typeof import('./src/components/CheckRow.vue')['default']
    ConnectSitePanel: typeof import('./src/components/ConnectSitePanel.vue')['default']
    DayCard: typeof import('./src/components/DayCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteDetailsDialog: typeof import('./src/components/SiteDetailsDialog.vue')['default']
  }
}
